[project]
name = "qfdn-main"
version = "0.1.2"
description = "Quantum Feedback Delay Networks"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy >=1.22",
    "matplotlib >=3.7",
    "qiskit>=2.0",
    "qiskit-aer",
    "sounddevice",
    "pylatexenc",
    "ipykernel",
]
